# -*- coding: utf-8 -*-
"""p3p.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JOSfvG-XIYCqJxq0nA2aV5SsY3Z8iNMF
"""

import tensorflow as tf
import matplotlib.pyplot as plt

from tensorflow.keras.datasets import fashion_mnist

(train_images, train_labels),(test_images, test_labels) = fashion_mnist.load_data()

def show_image(image, label):

    class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
                   'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

    plt.imshow(image, cmap='gray')
    plt.title(f"Label: {class_names[label]}")
    plt.show()

show_image(train_images[4], train_labels[4])

train_images = train_images / 255
test_images = test_images / 255

train_images = train_images[..., tf.newaxis]
test_images = test_images[..., tf.newaxis]



from tensorflow.keras.models import Sequential
from tensorflow.keras import layers

model = Sequential(layers=[
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

history = model.fit(train_images, train_labels, epochs=8, validation_split=0.1)

test_loss, test_acc = model.evaluate(test_images, test_labels, verbose=2)
print('\nTest accuracy:', test_acc)

img_to_disp = test_images[6].reshape((28, 28, 1))
img_to_pred = test_images[6].reshape((1, 28, 28, 1))

pred = model.predict(img_to_pred)
predicted_label = np.argmax(pred)
show_image(img_to_disp,predicted_label)

